-- Get all retiree titles

SELECT E.EMP_NO,
	E.FIRST_NAME,
	E.LAST_NAME,
	TI.TITLE,
	TI.FROM_DATE,
	TI.TO_DATE INTO RETIREMENT_TITLES
FROM EMPLOYEES AS E
INNER JOIN TITLES AS TI ON E.EMP_NO = TI.EMP_NO
WHERE (E.BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
ORDER BY E.EMP_NO;

-- Use Dictinct with Orderby to remove duplicate rows

SELECT DISTINCT ON (RT.EMP_NO) RT.EMP_NO,
	RT.FIRST_NAME,
	RT.LAST_NAME,
	RT.TITLE INTO UNIQUE_TITLES
FROM RETIREMENT_TITLES AS RT
WHERE (RT.TO_DATE = '9999-01-01')
ORDER BY RT.EMP_NO ASC,
	RT.TO_DATE DESC;

-- Retirees by title

SELECT COUNT(U.TITLE),
    U.TITLE INTO RETIREES_BY_TITLE
FROM UNIQUE_TITLES AS U
GROUP BY U.TITLE
ORDER BY COUNT(U.TITLE) DESC;